### ISSUE TITLE
Read all groups from searchbase and write it into MS SQL/other file

### ISSUE THREAD

**Issue by devnajan** [dfwarden/ActiveDirectory-Python#3]
@dfwarden, I am trying to read groups with atrributes from particulate search-base, and writing it into CSV file. But no luck. Please suggest, tried below code

---

import active_directory
import csv
for group in active_directory.search (objectClass='group','CN', 'description'):
  z = group
  #print z
def _get_all_of_objectClass(Connection, defaultNamingContext, objectClass):
    LDAP_query_string = ("Select \* ""from 'LDAP://%s' ""where objectClass = '%s'" % (defaultNamingContext,objectClass,))
    'LDAP_query_string: %r' % (LDAP_query_string,)
    L = list(LDAP_select_then_ADsPath_iterator(Connection, LDAP_query_string))  
    L.sort(key=_sort_helper)
    for d in L:

```
    print('\n')
    for k in ['CN', 'description']:
        v = d.get(k, '<<<MISSING>>>')
        print fill('%s: %s' % (k, v),initial_indent='    ',subsequent_indent='        ',)            
    for k in sorted(d.keys()):
        try:
            k = str(k)
        except UnicodeEncodeError:
            continue
        v = d[k]
        if v is UntranslatableCOM:
            continue
        try:
            v = str(v)
        except UnicodeEncodeError:
            v = repr(v)
```

with open('C:\file\newtestfil.csv','wb') as csvfile:
  writter = csv.writter(csvfile,delimiter = '',quotechar=',',
                        quoting= csv.QUOTE_MINIMAL)

**Comment by dfwarden** [comment]
I don't mean to be rude but are you sure you've got the right github repo? I ask because my class is "activedirectory" and I don't have a search() method. Could your active_directory object be an LDAPObject with the search() method from http://www.python-ldap.org/doc/html/ldap.html#ldap.LDAPObject.search perhaps?
